In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6869, 9359, 1830, 9992],
 [6869, 9359, 1830, 4945],
 [6869, 1197, 1830, 7657],
 [6561, 2618, 9378, 2008, 2707],
 [6561, 2618, 9378, 2008, 7603],
 [9135, 6869, 7159, 1830, 3306],
 [7377, 8696, 948, 2008]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6869 9359 1830 9992]
 [   0    0    0    0 6869 9359 1830 4945]
 [   0    0    0    0 6869 1197 1830 7657]
 [   0    0    0 6561 2618 9378 2008 2707]
 [   0    0    0 6561 2618 9378 2008 7603]
 [   0    0    0 9135 6869 7159 1830 3306]
 [   0    0    0    0 7377 8696  948 2008]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

e:\Generative AI\ANN\virtual_env\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 300ms/step


array([[[-1.40553825e-02, -1.04994699e-03,  3.56524065e-03,
          1.31480433e-02, -1.07881427e-02, -1.85557455e-03,
          1.52504109e-02, -3.94139178e-02,  3.63855250e-02,
          2.72603072e-02],
        [-1.40553825e-02, -1.04994699e-03,  3.56524065e-03,
          1.31480433e-02, -1.07881427e-02, -1.85557455e-03,
          1.52504109e-02, -3.94139178e-02,  3.63855250e-02,
          2.72603072e-02],
        [-1.40553825e-02, -1.04994699e-03,  3.56524065e-03,
          1.31480433e-02, -1.07881427e-02, -1.85557455e-03,
          1.52504109e-02, -3.94139178e-02,  3.63855250e-02,
          2.72603072e-02],
        [-1.40553825e-02, -1.04994699e-03,  3.56524065e-03,
          1.31480433e-02, -1.07881427e-02, -1.85557455e-03,
          1.52504109e-02, -3.94139178e-02,  3.63855250e-02,
          2.72603072e-02],
        [ 2.24936642e-02, -4.30824608e-03,  1.39979459e-02,
          1.43095516e-02,  4.60913666e-02,  6.99845701e-03,
         -2.25407612e-02,  3.99129502e-02, -4.892459

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6869, 9359, 1830, 9992], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>